workspace: true

stages:
  - lint 

jobs:
- name: Lint checking
  stage: lint
  image: androidsdk/android-29:latest
  environment:
    ROOM_ID: "158675752"
      # Insert the chatwork accounts which you want to mention when the pull request was verified
    MEMBERS: "[To:4070497] Tran Quang Huy"
  cache:
  - key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    paths:
      - ./gradle
  before_script:
  - chmod +x ./gradlew
  - echo "failed (pray)(sweat);(" > .msg_status
  - echo "(devil)" > .msg_icon
  script:
  - ./gradlew lint test
  - echo "successful (F)(F)(F)" > .msg_status
  - echo "(handshake)" > .msg_icon
  artifacts:
      paths:
        - app/build/reports
        - app/build/test-results
      expires_in: 3 days
  after_script:
  - echo "$CI_COMMIT_REF" | sed 's/refs//' > .pull_link
  - "curl -X POST -H \"X-ChatWorkToken: $CHATWORK_API_KEY\" -d \
                \"body= $MEMBERS [info][title]Repository : $CI_REPOSITORY $(cat .msg_icon)[/title]Your pull request is $(cat .msg_status) \n
              -> Click here for more detail: https://ci.sun-asterisk.com/$CI_GIT_PROVIDER/$CI_REPOSITORY/builds/$CI_BUILD_NUMBER \n
              - Author: $CI_COMMIT_AUTHOR \n
              - Pull request: https://$CI_GIT_PROVIDER.com/$CI_REPOSITORY$(cat .pull_link) [/info]
                \"\
                \"https://api.chatwork.com/v2/rooms/$ROOM_ID/messages\""
  only:
    branches:
    - develop
    - main
    - master
    events:
    - pull_request
