workspace: true

stages:
  - build

jobs:
- name: Build
  stage: build
  image: androidsdk/android-29:latest
  environment:
    JVM_OPTS: -Xmx3200m
      # This is Android review pull request box (Not necessary to change)
      ROOM_ID: "190272930"
      # Insert the chatwork accounts which you want to mention when the pull request was verified
      MEMBERS: ""
  cache:
  - key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    paths:
      - ~/.gradle
  before_script:
  - echo "Start job"
  - chmod +x ./gradlew
  script:
  - ./gradlew lint test
  artifacts:
      paths:
        - app/build/reports
        - app/build/test-results
      expires_in: 3 days
  after_script:
  - echo "Finish job"
  - if [[ true ]];  then
    curl -X POST -H "X-ChatWorkToken: $CHATWORK_API_KEY" -d \
                                        "body= $MEMBERS [info][title]Repository: $CIRCLE_PROJECT_REPONAME (problem)[/title]Your pull request is failed (pray)
    -> Click here for more detail: $CIRCLE_BUILD_URL
                                     - Branch: $CIRCLE_BRANCH
                                     - Pull request: $CIRCLE_PULL_REQUEST[/info]
                                       "\
                    "https://api.chatwork.com/v2/rooms/$ROOM_ID/messages"
    fi
  only:
    branches:
    - develop
    - main
    events:
    - pull_request
